config/routes.rb
Rails.application.routes.draw do
  resources :work_flow_transition_conditions
  resources :work_flow_process_tmps
  resources :work_flow_activity_definitions
  resources :user_upload_logs
  resources :user_info_to_branches
  resources :user_comments
  resources :us_states
  resources :title3s
  resources :title2s
  resources :title1s
  resources :titles
  resources :tff_to_tffgroups
  resources :template_form_fields
  resources :saved_publications
  resources :roletitles
  resources :registered_component_htmls
  resources :registered_components
  resources :publication_types
  resources :portrait_images
  resources :page_to_headline_assignments
  resources :page_contents
  resources :pages
  resources :order_status_trackers
  resources :migrations_locks
  resources :migrations
  resources :mediatypes
  resources :logins
  resources :lab_user_infos
  resources :lab_regions
  resources :lab_headlines
  resources :lab_complexes
  resources :lab_branches
  resources :lab_areas
  resources :lab_ad_sizes
  resources :join_user_to_assistants
  resources :imported_ma_news
  resources :imported_fa_news
  resources :import_new_branches
  resources :import_managers
  resources :import_ma_news
  resources :import_financial_advisors
  resources :import_fa_news
  resources :headlinecolortypes
  resources :headline_to_ad_size_assignments
  resources :function_to_group_assignments
  resources :form_field_values
  resources :form_field_types
  resources :featured_links
  resources :featured_headlines
  resources :export_users
  resources :excel_valid_params
  resources :eo_pk_tables
  resources :domains
  resources :diagnostics
  resources :designationformfieldvalues
  resources :designations
  resources :data_ref_types
  resources :data_ref2s
  resources :data_refs
  resources :customvalues
  resources :copied_categories
  resources :comment_to_orders
  resources :comments
  resources :clients
  resources :cdg_user_to_role_assignments
  resources :cdg_users
  resources :cdg_template_stage_data
  resources :cdg_templates
  resources :cdg_roles
  resources :cdg_permission_types
  resources :cdg_permissions
  resources :cdg_order_statuses
  resources :cdg_orders
  resources :cdg_nav_menu_items
  resources :cdg_function_groups
  resources :cdg_functions
  resources :cdg_faqs
  resources :cdg_configurations
  resources :category_to_categories
  resources :approval_details
  resources :additional_run_dates
  resources :ad_matrix_category_headlines
  resources :ad_matrix_categories
  resources :ad_library_nodes
  resources :activity_participant_assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'arfs/:id', action: :arf, controller: 'cdg_orders'
  get 'ingest_reports', action: :ingest_worm_reports, controller: 'cdg_orders'
  get 'generate_report', action: :csv_reports, controller: 'cdg_orders', defaults: { format: 'csv' }
  get 'create_package', action: :gather_and_compress_order, controller: 'cdg_orders'
  get '/', to: redirect('/cdg_orders')
end

app/models/cdg_permission.rb
class CdgPermission < ApplicationRecord
  belongs_to :fk_user_agent
  belongs_to :fk_function_resource
  belongs_to :fk_role_agent
  belongs_to :fk_function_group_resource
  belongs_to :fk_nav_menu_item_resource
  belongs_to :fk_permission_type
end

app/models/cdg_permission_type.rb
class CdgPermissionType < ApplicationRecord
  belongs_to :fk_permission_type
end

app/controllers/cdg_permissions_controller.rb
class CdgPermissionsController < ApplicationController
  before_action :set_cdg_permission, only: [:show, :edit, :update, :destroy]

  # GET /cdg_permissions
  # GET /cdg_permissions.json
  def index
    @cdg_permissions = CdgPermission.all
  end

  # GET /cdg_permissions/1
  # GET /cdg_permissions/1.json
  def show
  end

  # GET /cdg_permissions/new
  def new
    @cdg_permission = CdgPermission.new
  end

  # GET /cdg_permissions/1/edit
  def edit
  end

  # POST /cdg_permissions
  # POST /cdg_permissions.json
  def create
    @cdg_permission = CdgPermission.new(cdg_permission_params)

    respond_to do |format|
      if @cdg_permission.save
        format.html { redirect_to @cdg_permission, notice: 'Cdg permission was successfully created.' }
        format.json { render :show, status: :created, location: @cdg_permission }
      else
        format.html { render :new }
        format.json { render json: @cdg_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cdg_permissions/1
  # PATCH/PUT /cdg_permissions/1.json
  def update
    respond_to do |format|
      if @cdg_permission.update(cdg_permission_params)
        format.html { redirect_to @cdg_permission, notice: 'Cdg permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @cdg_permission }
      else
        format.html { render :edit }
        format.json { render json: @cdg_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cdg_permissions/1
  # DELETE /cdg_permissions/1.json
  def destroy
    @cdg_permission.destroy
    respond_to do |format|
      format.html { redirect_to cdg_permissions_url, notice: 'Cdg permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cdg_permission
      @cdg_permission = CdgPermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cdg_permission_params
      params.require(:cdg_permission).permit(:agent_type, :fk_user_agent_id, :fk_function_resource_id, :permission, :resource_type, :is_active, :fk_role_agent_id, :fk_function_group_resource_id, :fk_nav_menu_item_resource_id, :fk_permission_type_id)
    end
end

app/helpers/cdg_permissions_helper.rb
module CdgPermissionsHelper
end

app/views/cdg_permissions/_form.html.erb
<%= form_with(model: cdg_permission, local: true) do |form| %>
  <% if cdg_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cdg_permission.errors.count, "error") %> prohibited this cdg_permission from being saved:</h2>

      <ul>
      <% cdg_permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :agent_type %>
    <%= form.text_field :agent_type %>
  </div>

  <div class="field">
    <%= form.label :fk_user_agent_id %>
    <%= form.text_field :fk_user_agent_id %>
  </div>

  <div class="field">
    <%= form.label :fk_function_resource_id %>
    <%= form.text_field :fk_function_resource_id %>
  </div>

  <div class="field">
    <%= form.label :permission %>
    <%= form.text_field :permission %>
  </div>

  <div class="field">
    <%= form.label :resource_type %>
    <%= form.text_field :resource_type %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.text_field :is_active %>
  </div>

  <div class="field">
    <%= form.label :fk_role_agent_id %>
    <%= form.text_field :fk_role_agent_id %>
  </div>

  <div class="field">
    <%= form.label :fk_function_group_resource_id %>
    <%= form.text_field :fk_function_group_resource_id %>
  </div>

  <div class="field">
    <%= form.label :fk_nav_menu_item_resource_id %>
    <%= form.text_field :fk_nav_menu_item_resource_id %>
  </div>

  <div class="field">
    <%= form.label :fk_permission_type_id %>
    <%= form.text_field :fk_permission_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cdg_permissions/edit.html.erb
<h1>Editing Cdg Permission</h1>

<%= render 'form', cdg_permission: @cdg_permission %>

<%= link_to 'Show', @cdg_permission %> |
<%= link_to 'Back', cdg_permissions_path %>

app/views/cdg_permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cdg Permissions</h1>

<table>
  <thead>
    <tr>
      <th>Agent type</th>
      <th>Fk user agent</th>
      <th>Fk function resource</th>
      <th>Permission</th>
      <th>Resource type</th>
      <th>Is active</th>
      <th>Fk role agent</th>
      <th>Fk function group resource</th>
      <th>Fk nav menu item resource</th>
      <th>Fk permission type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cdg_permissions.each do |cdg_permission| %>
      <tr>
        <td><%= cdg_permission.agent_type %></td>
        <td><%= cdg_permission.fk_user_agent %></td>
        <td><%= cdg_permission.fk_function_resource %></td>
        <td><%= cdg_permission.permission %></td>
        <td><%= cdg_permission.resource_type %></td>
        <td><%= cdg_permission.is_active %></td>
        <td><%= cdg_permission.fk_role_agent %></td>
        <td><%= cdg_permission.fk_function_group_resource %></td>
        <td><%= cdg_permission.fk_nav_menu_item_resource %></td>
        <td><%= cdg_permission.fk_permission_type %></td>
        <td><%= link_to 'Show', cdg_permission %></td>
        <td><%= link_to 'Edit', edit_cdg_permission_path(cdg_permission) %></td>
        <td><%= link_to 'Destroy', cdg_permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cdg Permission', new_cdg_permission_path %>

app/views/cdg_permissions/new.html.erb
<h1>New Cdg Permission</h1>

<%= render 'form', cdg_permission: @cdg_permission %>

<%= link_to 'Back', cdg_permissions_path %>

app/views/cdg_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agent type:</strong>
  <%= @cdg_permission.agent_type %>
</p>

<p>
  <strong>Fk user agent:</strong>
  <%= @cdg_permission.fk_user_agent %>
</p>

<p>
  <strong>Fk function resource:</strong>
  <%= @cdg_permission.fk_function_resource %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @cdg_permission.permission %>
</p>

<p>
  <strong>Resource type:</strong>
  <%= @cdg_permission.resource_type %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @cdg_permission.is_active %>
</p>

<p>
  <strong>Fk role agent:</strong>
  <%= @cdg_permission.fk_role_agent %>
</p>

<p>
  <strong>Fk function group resource:</strong>
  <%= @cdg_permission.fk_function_group_resource %>
</p>

<p>
  <strong>Fk nav menu item resource:</strong>
  <%= @cdg_permission.fk_nav_menu_item_resource %>
</p>

<p>
  <strong>Fk permission type:</strong>
  <%= @cdg_permission.fk_permission_type %>
</p>

<%= link_to 'Edit', edit_cdg_permission_path(@cdg_permission) %> |
<%= link_to 'Back', cdg_permissions_path %>