config/routes.rb
Rails.application.routes.draw do
  resources :work_flow_transition_conditions
  resources :work_flow_process_tmps
  resources :work_flow_activity_definitions
  resources :user_upload_logs
  resources :user_info_to_branches
  resources :user_comments
  resources :us_states
  resources :title3s
  resources :title2s
  resources :title1s
  resources :titles
  resources :tff_to_tffgroups
  resources :template_form_fields
  resources :saved_publications
  resources :roletitles
  resources :registered_component_htmls
  resources :registered_components
  resources :publication_types
  resources :portrait_images
  resources :page_to_headline_assignments
  resources :page_contents
  resources :pages
  resources :order_status_trackers
  resources :migrations_locks
  resources :migrations
  resources :mediatypes
  resources :logins
  resources :lab_user_infos
  resources :lab_regions
  resources :lab_headlines
  resources :lab_complexes
  resources :lab_branches
  resources :lab_areas
  resources :lab_ad_sizes
  resources :join_user_to_assistants
  resources :imported_ma_news
  resources :imported_fa_news
  resources :import_new_branches
  resources :import_managers
  resources :import_ma_news
  resources :import_financial_advisors
  resources :import_fa_news
  resources :headlinecolortypes
  resources :headline_to_ad_size_assignments
  resources :function_to_group_assignments
  resources :form_field_values
  resources :form_field_types
  resources :featured_links
  resources :featured_headlines
  resources :export_users
  resources :excel_valid_params
  resources :eo_pk_tables
  resources :domains
  resources :diagnostics
  resources :designationformfieldvalues
  resources :designations
  resources :data_ref_types
  resources :data_ref2s
  resources :data_refs
  resources :customvalues
  resources :copied_categories
  resources :comment_to_orders
  resources :comments
  resources :clients
  resources :cdg_user_to_role_assignments
  resources :cdg_users
  resources :cdg_template_stage_data
  resources :cdg_templates
  resources :cdg_roles
  resources :cdg_permission_types
  resources :cdg_permissions
  resources :cdg_order_statuses
  resources :cdg_orders
  resources :cdg_nav_menu_items
  resources :cdg_function_groups
  resources :cdg_functions
  resources :cdg_faqs
  resources :cdg_configurations
  resources :category_to_categories
  resources :approval_details
  resources :additional_run_dates
  resources :ad_matrix_category_headlines
  resources :ad_matrix_categories
  resources :ad_library_nodes
  resources :activity_participant_assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'arfs/:id', action: :arf, controller: 'cdg_orders'
  get 'ingest_reports', action: :ingest_worm_reports, controller: 'cdg_orders'
  get 'generate_report', action: :csv_reports, controller: 'cdg_orders', defaults: { format: 'csv' }
  get 'create_package', action: :gather_and_compress_order, controller: 'cdg_orders'
  get '/', to: redirect('/cdg_orders')
end

app/models/cdg_function.rb
class CdgFunction < ApplicationRecord
end

app/controllers/cdg_functions_controller.rb
class CdgFunctionsController < ApplicationController
  before_action :set_cdg_function, only: [:show, :edit, :update, :destroy]

  # GET /cdg_functions
  # GET /cdg_functions.json
  def index
    @cdg_functions = CdgFunction.all
  end

  # GET /cdg_functions/1
  # GET /cdg_functions/1.json
  def show
  end

  # GET /cdg_functions/new
  def new
    @cdg_function = CdgFunction.new
  end

  # GET /cdg_functions/1/edit
  def edit
  end

  # POST /cdg_functions
  # POST /cdg_functions.json
  def create
    @cdg_function = CdgFunction.new(cdg_function_params)

    respond_to do |format|
      if @cdg_function.save
        format.html { redirect_to @cdg_function, notice: 'Cdg function was successfully created.' }
        format.json { render :show, status: :created, location: @cdg_function }
      else
        format.html { render :new }
        format.json { render json: @cdg_function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cdg_functions/1
  # PATCH/PUT /cdg_functions/1.json
  def update
    respond_to do |format|
      if @cdg_function.update(cdg_function_params)
        format.html { redirect_to @cdg_function, notice: 'Cdg function was successfully updated.' }
        format.json { render :show, status: :ok, location: @cdg_function }
      else
        format.html { render :edit }
        format.json { render json: @cdg_function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cdg_functions/1
  # DELETE /cdg_functions/1.json
  def destroy
    @cdg_function.destroy
    respond_to do |format|
      format.html { redirect_to cdg_functions_url, notice: 'Cdg function was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cdg_function
      @cdg_function = CdgFunction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cdg_function_params
      params.require(:cdg_function).permit(:sort_order, :name)
    end
end

app/helpers/cdg_functions_helper.rb
module CdgFunctionsHelper
end

app/views/cdg_functions/_form.html.erb
<%= form_with(model: cdg_function, local: true) do |form| %>
  <% if cdg_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cdg_function.errors.count, "error") %> prohibited this cdg_function from being saved:</h2>

      <ul>
      <% cdg_function.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sort_order %>
    <%= form.number_field :sort_order %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cdg_functions/edit.html.erb
<h1>Editing Cdg Function</h1>

<%= render 'form', cdg_function: @cdg_function %>

<%= link_to 'Show', @cdg_function %> |
<%= link_to 'Back', cdg_functions_path %>

app/views/cdg_functions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cdg Functions</h1>

<table>
  <thead>
    <tr>
      <th>Sort order</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cdg_functions.each do |cdg_function| %>
      <tr>
        <td><%= cdg_function.sort_order %></td>
        <td><%= cdg_function.name %></td>
        <td><%= link_to 'Show', cdg_function %></td>
        <td><%= link_to 'Edit', edit_cdg_function_path(cdg_function) %></td>
        <td><%= link_to 'Destroy', cdg_function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cdg Function', new_cdg_function_path %>

app/views/cdg_functions/new.html.erb
<h1>New Cdg Function</h1>

<%= render 'form', cdg_function: @cdg_function %>

<%= link_to 'Back', cdg_functions_path %>

app/views/cdg_functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sort order:</strong>
  <%= @cdg_function.sort_order %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cdg_function.name %>
</p>

<%= link_to 'Edit', edit_cdg_function_path(@cdg_function) %> |
<%= link_to 'Back', cdg_functions_path %>