config/routes.rb
Rails.application.routes.draw do
  resources :work_flow_transition_conditions
  resources :work_flow_process_tmps
  resources :work_flow_activity_definitions
  resources :user_upload_logs
  resources :user_info_to_branches
  resources :user_comments
  resources :us_states
  resources :title3s
  resources :title2s
  resources :title1s
  resources :titles
  resources :tff_to_tffgroups
  resources :template_form_fields
  resources :saved_publications
  resources :roletitles
  resources :registered_component_htmls
  resources :registered_components
  resources :publication_types
  resources :portrait_images
  resources :page_to_headline_assignments
  resources :page_contents
  resources :pages
  resources :order_status_trackers
  resources :migrations_locks
  resources :migrations
  resources :mediatypes
  resources :logins
  resources :lab_user_infos
  resources :lab_regions
  resources :lab_headlines
  resources :lab_complexes
  resources :lab_branches
  resources :lab_areas
  resources :lab_ad_sizes
  resources :join_user_to_assistants
  resources :imported_ma_news
  resources :imported_fa_news
  resources :import_new_branches
  resources :import_managers
  resources :import_ma_news
  resources :import_financial_advisors
  resources :import_fa_news
  resources :headlinecolortypes
  resources :headline_to_ad_size_assignments
  resources :function_to_group_assignments
  resources :form_field_values
  resources :form_field_types
  resources :featured_links
  resources :featured_headlines
  resources :export_users
  resources :excel_valid_params
  resources :eo_pk_tables
  resources :domains
  resources :diagnostics
  resources :designationformfieldvalues
  resources :designations
  resources :data_ref_types
  resources :data_ref2s
  resources :data_refs
  resources :customvalues
  resources :copied_categories
  resources :comment_to_orders
  resources :comments
  resources :clients
  resources :cdg_user_to_role_assignments
  resources :cdg_users
  resources :cdg_template_stage_data
  resources :cdg_templates
  resources :cdg_roles
  resources :cdg_permission_types
  resources :cdg_permissions
  resources :cdg_order_statuses
  resources :cdg_orders
  resources :cdg_nav_menu_items
  resources :cdg_function_groups
  resources :cdg_functions
  resources :cdg_faqs
  resources :cdg_configurations
  resources :category_to_categories
  resources :approval_details
  resources :additional_run_dates
  resources :ad_matrix_category_headlines
  resources :ad_matrix_categories
  resources :ad_library_nodes
  resources :activity_participant_assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'arfs/:id', action: :arf, controller: 'cdg_orders'
  get 'ingest_reports', action: :ingest_worm_reports, controller: 'cdg_orders'
  get 'generate_report', action: :csv_reports, controller: 'cdg_orders', defaults: { format: 'csv' }
  get 'create_package', action: :gather_and_compress_order, controller: 'cdg_orders'
  get '/', to: redirect('/cdg_orders')
end

app/models/featured_headline.rb
class FeaturedHeadline < ApplicationRecord
  belongs_to :fk_headline
end

app/controllers/featured_headlines_controller.rb
class FeaturedHeadlinesController < ApplicationController
  before_action :set_featured_headline, only: [:show, :edit, :update, :destroy]

  # GET /featured_headlines
  # GET /featured_headlines.json
  def index
    @featured_headlines = FeaturedHeadline.all
  end

  # GET /featured_headlines/1
  # GET /featured_headlines/1.json
  def show
  end

  # GET /featured_headlines/new
  def new
    @featured_headline = FeaturedHeadline.new
  end

  # GET /featured_headlines/1/edit
  def edit
  end

  # POST /featured_headlines
  # POST /featured_headlines.json
  def create
    @featured_headline = FeaturedHeadline.new(featured_headline_params)

    respond_to do |format|
      if @featured_headline.save
        format.html { redirect_to @featured_headline, notice: 'Featured headline was successfully created.' }
        format.json { render :show, status: :created, location: @featured_headline }
      else
        format.html { render :new }
        format.json { render json: @featured_headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /featured_headlines/1
  # PATCH/PUT /featured_headlines/1.json
  def update
    respond_to do |format|
      if @featured_headline.update(featured_headline_params)
        format.html { redirect_to @featured_headline, notice: 'Featured headline was successfully updated.' }
        format.json { render :show, status: :ok, location: @featured_headline }
      else
        format.html { render :edit }
        format.json { render json: @featured_headline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_headlines/1
  # DELETE /featured_headlines/1.json
  def destroy
    @featured_headline.destroy
    respond_to do |format|
      format.html { redirect_to featured_headlines_url, notice: 'Featured headline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_featured_headline
      @featured_headline = FeaturedHeadline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def featured_headline_params
      params.require(:featured_headline).permit(:tag_line, :headline_sort_order, :fk_headline_id)
    end
end

app/helpers/featured_headlines_helper.rb
module FeaturedHeadlinesHelper
end

app/views/featured_headlines/_form.html.erb
<%= form_with(model: featured_headline, local: true) do |form| %>
  <% if featured_headline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(featured_headline.errors.count, "error") %> prohibited this featured_headline from being saved:</h2>

      <ul>
      <% featured_headline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_line %>
    <%= form.text_field :tag_line %>
  </div>

  <div class="field">
    <%= form.label :headline_sort_order %>
    <%= form.number_field :headline_sort_order %>
  </div>

  <div class="field">
    <%= form.label :fk_headline_id %>
    <%= form.text_field :fk_headline_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/featured_headlines/edit.html.erb
<h1>Editing Featured Headline</h1>

<%= render 'form', featured_headline: @featured_headline %>

<%= link_to 'Show', @featured_headline %> |
<%= link_to 'Back', featured_headlines_path %>

app/views/featured_headlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Featured Headlines</h1>

<table>
  <thead>
    <tr>
      <th>Tag line</th>
      <th>Headline sort order</th>
      <th>Fk headline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @featured_headlines.each do |featured_headline| %>
      <tr>
        <td><%= featured_headline.tag_line %></td>
        <td><%= featured_headline.headline_sort_order %></td>
        <td><%= featured_headline.fk_headline %></td>
        <td><%= link_to 'Show', featured_headline %></td>
        <td><%= link_to 'Edit', edit_featured_headline_path(featured_headline) %></td>
        <td><%= link_to 'Destroy', featured_headline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Featured Headline', new_featured_headline_path %>

app/views/featured_headlines/new.html.erb
<h1>New Featured Headline</h1>

<%= render 'form', featured_headline: @featured_headline %>

<%= link_to 'Back', featured_headlines_path %>

app/views/featured_headlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag line:</strong>
  <%= @featured_headline.tag_line %>
</p>

<p>
  <strong>Headline sort order:</strong>
  <%= @featured_headline.headline_sort_order %>
</p>

<p>
  <strong>Fk headline:</strong>
  <%= @featured_headline.fk_headline %>
</p>

<%= link_to 'Edit', edit_featured_headline_path(@featured_headline) %> |
<%= link_to 'Back', featured_headlines_path %>