config/routes.rb
Rails.application.routes.draw do
  resources :work_flow_transition_conditions
  resources :work_flow_process_tmps
  resources :work_flow_activity_definitions
  resources :user_upload_logs
  resources :user_info_to_branches
  resources :user_comments
  resources :us_states
  resources :title3s
  resources :title2s
  resources :title1s
  resources :titles
  resources :tff_to_tffgroups
  resources :template_form_fields
  resources :saved_publications
  resources :roletitles
  resources :registered_component_htmls
  resources :registered_components
  resources :publication_types
  resources :portrait_images
  resources :page_to_headline_assignments
  resources :page_contents
  resources :pages
  resources :order_status_trackers
  resources :migrations_locks
  resources :migrations
  resources :mediatypes
  resources :logins
  resources :lab_user_infos
  resources :lab_regions
  resources :lab_headlines
  resources :lab_complexes
  resources :lab_branches
  resources :lab_areas
  resources :lab_ad_sizes
  resources :join_user_to_assistants
  resources :imported_ma_news
  resources :imported_fa_news
  resources :import_new_branches
  resources :import_managers
  resources :import_ma_news
  resources :import_financial_advisors
  resources :import_fa_news
  resources :headlinecolortypes
  resources :headline_to_ad_size_assignments
  resources :function_to_group_assignments
  resources :form_field_values
  resources :form_field_types
  resources :featured_links
  resources :featured_headlines
  resources :export_users
  resources :excel_valid_params
  resources :eo_pk_tables
  resources :domains
  resources :diagnostics
  resources :designationformfieldvalues
  resources :designations
  resources :data_ref_types
  resources :data_ref2s
  resources :data_refs
  resources :customvalues
  resources :copied_categories
  resources :comment_to_orders
  resources :comments
  resources :clients
  resources :cdg_user_to_role_assignments
  resources :cdg_users
  resources :cdg_template_stage_data
  resources :cdg_templates
  resources :cdg_roles
  resources :cdg_permission_types
  resources :cdg_permissions
  resources :cdg_order_statuses
  resources :cdg_orders
  resources :cdg_nav_menu_items
  resources :cdg_function_groups
  resources :cdg_functions
  resources :cdg_faqs
  resources :cdg_configurations
  resources :category_to_categories
  resources :approval_details
  resources :additional_run_dates
  resources :ad_matrix_category_headlines
  resources :ad_matrix_categories
  resources :ad_library_nodes
  resources :activity_participant_assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'arfs/:id', action: :arf, controller: 'cdg_orders'
  get 'ingest_reports', action: :ingest_worm_reports, controller: 'cdg_orders'
  get 'generate_report', action: :csv_reports, controller: 'cdg_orders', defaults: { format: 'csv' }
  get 'create_package', action: :gather_and_compress_order, controller: 'cdg_orders'
  get '/', to: redirect('/cdg_orders')
end

app/models/excel_valid_param.rb
class ExcelValidParam < ApplicationRecord
end

app/controllers/excel_valid_params_controller.rb
class ExcelValidParamsController < ApplicationController
  before_action :set_excel_valid_param, only: [:show, :edit, :update, :destroy]

  # GET /excel_valid_params
  # GET /excel_valid_params.json
  def index
    @excel_valid_params = ExcelValidParam.all
  end

  # GET /excel_valid_params/1
  # GET /excel_valid_params/1.json
  def show
  end

  # GET /excel_valid_params/new
  def new
    @excel_valid_param = ExcelValidParam.new
  end

  # GET /excel_valid_params/1/edit
  def edit
  end

  # POST /excel_valid_params
  # POST /excel_valid_params.json
  def create
    @excel_valid_param = ExcelValidParam.new(excel_valid_param_params)

    respond_to do |format|
      if @excel_valid_param.save
        format.html { redirect_to @excel_valid_param, notice: 'Excel valid param was successfully created.' }
        format.json { render :show, status: :created, location: @excel_valid_param }
      else
        format.html { render :new }
        format.json { render json: @excel_valid_param.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excel_valid_params/1
  # PATCH/PUT /excel_valid_params/1.json
  def update
    respond_to do |format|
      if @excel_valid_param.update(excel_valid_param_params)
        format.html { redirect_to @excel_valid_param, notice: 'Excel valid param was successfully updated.' }
        format.json { render :show, status: :ok, location: @excel_valid_param }
      else
        format.html { render :edit }
        format.json { render json: @excel_valid_param.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excel_valid_params/1
  # DELETE /excel_valid_params/1.json
  def destroy
    @excel_valid_param.destroy
    respond_to do |format|
      format.html { redirect_to excel_valid_params_url, notice: 'Excel valid param was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excel_valid_param
      @excel_valid_param = ExcelValidParam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excel_valid_param_params
      params.require(:excel_valid_param).permit(:is_required, :excel_col_name, :excel_col_number, :type)
    end
end

app/helpers/excel_valid_params_helper.rb
module ExcelValidParamsHelper
end

app/views/excel_valid_params/_form.html.erb
<%= form_with(model: excel_valid_param, local: true) do |form| %>
  <% if excel_valid_param.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(excel_valid_param.errors.count, "error") %> prohibited this excel_valid_param from being saved:</h2>

      <ul>
      <% excel_valid_param.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_required %>
    <%= form.text_field :is_required %>
  </div>

  <div class="field">
    <%= form.label :excel_col_name %>
    <%= form.text_field :excel_col_name %>
  </div>

  <div class="field">
    <%= form.label :excel_col_number %>
    <%= form.number_field :excel_col_number %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/excel_valid_params/edit.html.erb
<h1>Editing Excel Valid Param</h1>

<%= render 'form', excel_valid_param: @excel_valid_param %>

<%= link_to 'Show', @excel_valid_param %> |
<%= link_to 'Back', excel_valid_params_path %>

app/views/excel_valid_params/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Excel Valid Params</h1>

<table>
  <thead>
    <tr>
      <th>Is required</th>
      <th>Excel col name</th>
      <th>Excel col number</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @excel_valid_params.each do |excel_valid_param| %>
      <tr>
        <td><%= excel_valid_param.is_required %></td>
        <td><%= excel_valid_param.excel_col_name %></td>
        <td><%= excel_valid_param.excel_col_number %></td>
        <td><%= excel_valid_param.type %></td>
        <td><%= link_to 'Show', excel_valid_param %></td>
        <td><%= link_to 'Edit', edit_excel_valid_param_path(excel_valid_param) %></td>
        <td><%= link_to 'Destroy', excel_valid_param, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excel Valid Param', new_excel_valid_param_path %>

app/views/excel_valid_params/new.html.erb
<h1>New Excel Valid Param</h1>

<%= render 'form', excel_valid_param: @excel_valid_param %>

<%= link_to 'Back', excel_valid_params_path %>

app/views/excel_valid_params/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is required:</strong>
  <%= @excel_valid_param.is_required %>
</p>

<p>
  <strong>Excel col name:</strong>
  <%= @excel_valid_param.excel_col_name %>
</p>

<p>
  <strong>Excel col number:</strong>
  <%= @excel_valid_param.excel_col_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @excel_valid_param.type %>
</p>

<%= link_to 'Edit', edit_excel_valid_param_path(@excel_valid_param) %> |
<%= link_to 'Back', excel_valid_params_path %>